### ISSUE TITLE
Async Issue

### ISSUE THREAD

**Issue by joshuamcginnis** [ysugimoto/aws-lambda-image#41]
How do you handle the case where a user requests an image that hasn't completed processing yet?

**Comment by odedniv** [comment]
I believe S3 doesn't broadcast the event until after the file has been fully uploaded to S3, partial files handling never happened to me.

**Comment by kdybicz** [comment]
@joshuamcginnis I guess this could have something to do with S3 event handler. What event type did you set in it?

**Comment by ashe540** [comment]
I'm having the same issue. After saving the original image to S3, the lambda function to resize kicks in. But it takes a while to process, hence the user in the application will see a broken link since the image hasn't been processed yet. Any ideas how we could handle this? I'm considering issuing a request via my application's API to update the image's link once the lambda function finishes, but I'm not sure if there's a better way to do this.

**Comment by kdybicz** [comment]
@joshuamcginnis sorry for not really helpful answer, response from @odedniv did tricked me a bit here :) In you case, same as for @ashe540 I can suggest [Google](https://www.google.com/search?q=javascript+reload+failed+images), at least if you want to follow KISS rule.
