### ISSUE TITLE
Replace original files

### ISSUE THREAD

**Issue by scottybo** [ysugimoto/aws-lambda-image#43]
Hi,

Just wondering if it's possible to overwrite the original images rather than putting them into a different bucket?

Any instructions would be hugely appreciated!

**Comment by arthurlataks** [comment]
Hi, it is rather easy, yet I would not suggest that if you are using CDN, because image processing with lambda will happen synchronously, so non-reduced images will be cached and reduced images will be available only after cache expires for that edge location.

But if you are still willing to do that you need to take a look [here](https://github.com/ysugimoto/aws-lambda-image/blob/master/libs/ImageReducer.js#L47), this is the place where image name for the file is decided, if you need to overwrite the original one with the reduced or resized and reduced one - just change it to `image.getFileName()`, but keep in mind that both actions (resize and reduce), do use reduce class, take a look [here](https://github.com/ysugimoto/aws-lambda-image/blob/master/libs/ImageProcessor.js#L100), so yeah, keep in mind, that if you will need to have different key for resized images, you will need to set it in the function I just recently mentioned.

To be honest code is written very well, huge thanks to @ysugimoto, so there should be no issues with adjusting the package.

**Comment by scottybo** [comment]
Brilliant, thank you! We're not using a cdn (yet) so will keep that in mind. We're only using the reduce option as image resizing happens via WordPress, so this should work perfectly! Will give it a try in the morning :)

**Comment by scottybo** [comment]
Given it a go this morning - it seems to be doing something funky with the directories

My config is as follows:

`
{
  "bucket": "webpager",
  "reduce": {

  }
}
`

Let's say I uploaded a file to /uploads

When it gets compressed it gets put in a new folder /uploads/uploads.

If I upload to the root of the bucket, it replaces the original file fine.

Any ideas? :)

**Comment by scottybo** [comment]
Aha! Figured it out - hadn't followed your instructions properly, the entire line you mentioned should be set to image.getFileName() instead of dir + image.getFileName(),

**Comment by arthurlataks** [comment]
@scottybo Ok, noted, next time will be more specific. Glad you worked it out in the end :)

**Comment by jaketoolson** [comment]
@scottybo what did you end up doing?
